# Generated by Django 2.0.2 on 2019-01-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190106_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='myimage',
            new_name='image',
        ),
    ]
